# Generated by Django 5.2 on 2025-04-09 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_id", models.CharField(max_length=50, unique=True)),
                ("width", models.FloatField()),
                ("depth", models.FloatField()),
                ("height", models.FloatField()),
                ("is_undocking", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("width", models.FloatField()),
                ("depth", models.FloatField()),
                ("height", models.FloatField()),
                ("mass", models.FloatField()),
                ("priority", models.IntegerField(default=50)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("usage_limit", models.IntegerField(blank=True, null=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("is_waste", models.BooleanField(default=False)),
                ("position_width", models.FloatField(blank=True, null=True)),
                ("position_depth", models.FloatField(blank=True, null=True)),
                ("position_height", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="cargoapp.container",
                    ),
                ),
                (
                    "preferred_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cargoapp.zone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlacementLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cargoapp.container",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cargoapp.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RetrievalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cargoapp.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UndockingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("items_removed", models.IntegerField()),
                ("total_volume", models.FloatField()),
                ("total_weight", models.FloatField()),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cargoapp.container",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="container",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="containers",
                to="cargoapp.zone",
            ),
        ),
    ]
